# Generated by Django 3.0.6 on 2021-02-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Completed',
        ),
    ]
