# Generated by Django 3.0.6 on 2021-02-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210202_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='datetime',
        ),
    ]
